import type { FeaturedCategory, ShowcaseProduct, ValuePoint } from "@/types/content";

export const FEATURED_CATEGORIES: FeaturedCategory[] = [
  {
    slug: "fitness-equipment",
    name: "Fitness Equipment",
    description: "Core equipment for gym floors, studios, and fitness programs.",
    image: "/catalog/category-fitness-equipment.svg",
    brandDivision: "rox-fitness",
    accent: "red",
    productCountLabel: "Rox Fitness",
  },
  {
    slug: "strength-training",
    name: "Strength Training",
    description: "Weights, resistance products, and durable strength-focused essentials.",
    image: "/catalog/category-strength-training.svg",
    brandDivision: "rox-fitness",
    accent: "dark",
    productCountLabel: "Bulk ready",
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "High-rotation training accessories for everyday sports retail demand.",
    image: "/catalog/category-accessories.svg",
    brandDivision: "rox-fitness",
    accent: "light",
    productCountLabel: "Fast moving",
  },
  {
    slug: "board-games",
    name: "Board Games",
    description: "Family, strategy, and classic tabletop products for broad shelf appeal.",
    image: "/catalog/category-board-games.svg",
    brandDivision: "nex-games",
    accent: "light",
    productCountLabel: "Nex Games",
  },
  {
    slug: "indoor-games",
    name: "Indoor Games",
    description: "Compact indoor play products built for homes, clubs, and game rooms.",
    image: "/catalog/category-indoor-games.svg",
    brandDivision: "nex-games",
    accent: "dark",
    productCountLabel: "Game sets",
  },
  {
    slug: "sports-games",
    name: "Sports Games",
    description: "Game-led sports products with strong recreational and retail demand.",
    image: "/catalog/category-sports-games.svg",
    brandDivision: "nex-games",
    accent: "red",
    productCountLabel: "Play focused",
  },
];

export const HOMEPAGE_PRODUCTS: ShowcaseProduct[] = [
  {
    slug: "rox-pro-resistance-set",
    name: "Rox Pro Resistance Set",
    shortDescription: "Multi-level resistance kit for studios and home training bundles.",
    description:
      "A compact resistance set made for strength warmups, daily movement, and flexible training routines.",
    brandDivision: "rox-fitness",
    category: "Fitness Equipment",
    regularPrice: 28,
    salePrice: 24,
    stockQuantity: 240,
    stockStatus: "in-stock",
    thumbnail: "/catalog/product-resistance-set.svg",
    images: [{ url: "/catalog/product-resistance-set.svg", alt: "Rox Pro Resistance Set" }],
    badge: "Featured pick",
    visualTone: "red",
  },
  {
    slug: "rox-rubber-dumbbell-10kg",
    name: "Rox Rubber Dumbbell 10kg",
    shortDescription: "Commercial-feel rubber coated dumbbell for strength assortments.",
    description:
      "Rubber coated 10kg dumbbell with a clean grip profile for repeat strength sessions.",
    brandDivision: "rox-fitness",
    category: "Strength Training",
    regularPrice: 42,
    stockQuantity: 72,
    stockStatus: "low-stock",
    thumbnail: "/catalog/product-dumbbell.svg",
    images: [{ url: "/catalog/product-dumbbell.svg", alt: "Rox Rubber Dumbbell 10kg" }],
    badge: "Rox Fitness",
    visualTone: "dark",
  },
  {
    slug: "nex-classic-board-game-set",
    name: "Nex Classic Board Game Set",
    shortDescription: "Retail-ready tabletop game set for family and indoor play ranges.",
    description:
      "A classic tabletop game set for relaxed indoor play, simple display, and easy browsing.",
    brandDivision: "nex-games",
    category: "Board Games",
    regularPrice: 18,
    stockQuantity: 310,
    stockStatus: "in-stock",
    thumbnail: "/catalog/product-board-game.svg",
    images: [{ url: "/catalog/product-board-game.svg", alt: "Nex Classic Board Game Set" }],
    badge: "Nex Games",
    visualTone: "light",
  },
  {
    slug: "nex-indoor-target-game",
    name: "Nex Indoor Target Game",
    shortDescription: "Compact skill game for recreational sports and game room shelves.",
    description:
      "A compact target game designed for indoor recreation, skill practice, and quick setup.",
    brandDivision: "nex-games",
    category: "Indoor Games",
    regularPrice: 32,
    priceDisplay: "Tier pricing available",
    stockQuantity: 0,
    stockStatus: "out-of-stock",
    thumbnail: "/catalog/product-target-game.svg",
    images: [{ url: "/catalog/product-target-game.svg", alt: "Nex Indoor Target Game" }],
    badge: "Restocking",
    visualTone: "red",
  },
];

export const VALUE_POINTS: ValuePoint[] = [
  {
    title: "Wide Product Range",
    description: "Fitness, indoor games, board games, and sports products in one focused catalog.",
  },
  {
    title: "Product Catalog",
    description: "Built for customers reviewing availability, pricing, and specifications before contact.",
  },
  {
    title: "Quality-focused Products",
    description: "A premium presentation layer for product ranges that need buyer confidence.",
  },
  {
    title: "Updated Stock Information",
    description: "The data model is ready for live stock states and catalog refreshes.",
  },
];
